/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AvatarSelect {
    'avatar': string;
    'drop': boolean;
    'opciones': string;
  }
}

declare global {


  interface HTMLAvatarSelectElement extends Components.AvatarSelect, HTMLStencilElement {}
  var HTMLAvatarSelectElement: {
    prototype: HTMLAvatarSelectElement;
    new (): HTMLAvatarSelectElement;
  };
  interface HTMLElementTagNameMap {
    'avatar-select': HTMLAvatarSelectElement;
  }
}

declare namespace LocalJSX {
  interface AvatarSelect extends JSXBase.HTMLAttributes<HTMLAvatarSelectElement> {
    'avatar'?: string;
    'drop'?: boolean;
    'onAvatarSelected'?: (event: CustomEvent<any>) => void;
    'opciones'?: string;
  }

  interface IntrinsicElements {
    'avatar-select': AvatarSelect;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


