/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface AvatarSelect {
    'alignment': string;
    'avatar': string;
    'customClass': string;
    'dark_mode': boolean;
    'drop': boolean;
  }
}

declare global {


  interface HTMLAvatarSelectElement extends Components.AvatarSelect, HTMLStencilElement {}
  var HTMLAvatarSelectElement: {
    prototype: HTMLAvatarSelectElement;
    new (): HTMLAvatarSelectElement;
  };
  interface HTMLElementTagNameMap {
    'avatar-select': HTMLAvatarSelectElement;
  }
}

declare namespace LocalJSX {
  interface AvatarSelect extends JSXBase.HTMLAttributes<HTMLAvatarSelectElement> {
    'alignment'?: string;
    'avatar'?: string;
    'customClass'?: string;
    'dark_mode'?: boolean;
    'drop'?: boolean;
    'onAvatarSelected'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'avatar-select': AvatarSelect;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


